### ISSUE TITLE
页面切换时bug

### ISSUE THREAD

**Issue by Grayon** [gsdios/SDCycleScrollView#113]
当轮播动画时发生页面切换，返回轮播图片会卡在一半，等计时器事件发生才能恢复

**Comment by gsdios** [comment]
好的，我随后看下

**Comment by chenZai90** [comment]
我也遇到了这个问题。就是只有一张图片的时候，界面来回切换之后在返回到当前有轮播图的这个界面就会卡在一半，而且是偶尔会出现不是必现的。
