### ISSUE TITLE
更改了SDWebImage后缓存有问题

### ISSUE THREAD

**Issue by maxwell44** [gsdios/SDCycleScrollView#115]
更改了SDWebImage后缓存有问题,图片显示不正常..
我Debug后.发现我的数据源URL地址是正确的.但缓存的图片却是一张不知道哪来的图片

**Comment by gsdios** [comment]
吧 缓存 清除掉 重新试一下看看

**Comment by maxwell44** [comment]
清除了缓存...也没用....

**Comment by gsdios** [comment]
新建QQ交流群：185534916，加入下反馈下你的问题
