### ISSUE TITLE
UICollectionViewCell结构，以及自定义内容添加到cell的哪层view

### ISSUE THREAD

**Issue by Forfre** [gsdios/SDCycleScrollView#116]
下面内容引自喵神博客：
http://onevcat.com/2012/06/introducing-collection-views/

****************************************
**关于Cell**

相对于UITableViewCell来说，UICollectionViewCell没有这么多花头。首先UICollectionViewCell不存在各式各样的默认的style，这主要是由于展示对象的性质决定的，因为UICollectionView所用来展示的对象相比UITableView来说要来得灵活，大部分情况下更偏向于图像而非文字，因此需求将会千奇百怪。因此SDK提供给我们的默认的UICollectionViewCell结构上相对比较简单，由下至上：

首先是cell本身作为容器view
然后是一个大小自动适应整个cell的backgroundView，用作cell平时的背景
再其上是selectedBackgroundView，是cell被选中时的背景
**最后是一个contentView，自定义内容应被加在这个view上**

****************************************
**自定义SDCollectionViewCell.m中:**
[self addSubview:imageView];
[self addSubview:titleLabel];

**Comment by gsdios** [comment]
好的，感谢细心的观察以及反馈，我一直也是习惯把所有控件都添加在cell的 contentview里面的，可能当时疏忽了，多谢提醒

**Comment by gsdios** [comment]
另外，应该是在ios7 以后在cell里面调用addsubview会自动添加到contentview里面，但是ios7以及以前应该没有这样操作
