### ISSUE TITLE
自封第一，你们中国人真是呵呵

### ISSUE THREAD

**Issue by fooevr** [gsdios/SDCycleScrollView#124]

**Comment by gsdios** [comment]
请列举出一个 比这个自动轮播库 star 更多 或者 cocoapods 下载量更多的库，要不然的话这个“第一”会一直标注下去，直到你列举出来。

**Comment by fooevr** [comment]
呵呵，预想中的一套撕逼套路，您随意。

**Comment by gsdios** [comment]
你既然提出异议，就请给出个可以称得上第一的标准，否则你的 issue 毫无意义，纯粹在扯淡而已吗？

**Comment by fooevr** [comment]
你觉得我是在跟你讨论你配不配得上第一？还没做出点成绩就牛逼哄哄的自封为王了，是做技术该有的态度？

**Comment by huyahui** [comment]
这个歪果仁中文不错

**Comment by gsdios** [comment]
看来真的是纯粹来扯淡的，鉴定完毕！写出来“第一”只是为了让使用这个库的人知道这个库是被众多开发者广泛采用和推荐的，并且我会经常维护，希望想要使用此库的开发者可以打消其他顾虑而已，不知道为什么到你这里会有如此大的反应，能不能告知下到底是什么样一种心理呢？

**Comment by SuperManPLA** [comment]
挺不错的库啊,而且作者很负责任,一直在维护,我一直在用呢,之前的老版本不好用,很容易造成崩溃,需要改代码才行,现在的版本几乎嵌入到项目里就可以了,我还没遇到什么问题,支持一下作者
