### ISSUE TITLE
手动滑动图片没有触发代理方法 cycleScrollView:didScrollToIndex:index

### ISSUE THREAD

**Issue by zengyuanchen** [gsdios/SDCycleScrollView#130]
当用户手动滑动图片的时候 不会触发代理方法
- (void)cycleScrollView:(SDCycleScrollView *)cycleScrollView didScrollToIndex:(NSInteger)index

**看源码发现scrollViewDidScroll中没有去调用didScrollToIndex代理方法，建议添加**
- (void)scrollViewDidScroll:(UIScrollView *)scrollView

**Comment by gsdios** [comment]
好的，收到反馈，已经修复

**Comment by zengyuanchen** [comment]
我更新了v1.61版本
问题还在，没有修复，烦请抽时间看看

**Comment by gsdios** [comment]
这个确实已经修改过了，只是还没有更新pod上的版本，我随后更新下，你可以先下载代码测试下，感谢关注与反馈！
