### ISSUE TITLE
设置了自动滚动,为什么没有自动滚动,我手动滑动一张后才开始自动滚动?

### ISSUE THREAD

**Issue by GLei1122** [gsdios/SDCycleScrollView#133]
我在首页加了一个我自己的无线滚动.是不是这个原因啊导致runloop没有立即开启?

**Comment by gsdios** [comment]
如果 sdcyclescrollview 中途 有被移出过 父view，需要在再次 加入到 父view时候 调用一次 autoScroll = yes，，具体原理 看 代码即可知晓
