### ISSUE TITLE
本地或者网络设置显示一张图片的时候显示会有问题

### ISSUE THREAD

**Issue by chennyhuang** [gsdios/SDCycleScrollView#15]
我尝试加了一个判断
- (void)setImagesGroup:(NSMutableArray *)imagesGroup
{
    _imagesGroup = imagesGroup;
    _totalItemsCount = imagesGroup.count * 100;
    if (_imagesGroup.count == 1) {
        _mainView.scrollEnabled = NO;
        return;
    }
    [self setupTimer];
    [self setupPageControl];
    [self.mainView reloadData];
}

**Comment by gsdios** [comment]
好的，收到反馈，谢谢您的关注与支持。
