### ISSUE TITLE
ios9.3 xcode7.3在4S的模拟器下显示不出图片。。。

### ISSUE THREAD

**Issue by app-lab** [gsdios/SDCycleScrollView#150]
<Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set 
CG_CONTEXT_SHOW_BACKTRACE environmental variable.

<Error>: CGBitmapContextCreateImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.

**Comment by gsdios** [comment]
这个应该不是sdcyclescrollview报出的错，检查下你的其他地方的代码看下
