### ISSUE TITLE
self.backgroundImageView这个 imageview有点问题 您看下

### ISSUE THREAD

**Issue by xmt0615** [gsdios/SDCycleScrollView#151]
- (void)setPlaceholderImage:(UIImage *)placeholderImage
{
    _placeholderImage = placeholderImage;
    
    if (!self.backgroundImageView && self.imageURLStringsGroup.count == 0) {
        UIImageView *bgImageView = [UIImageView new];
        bgImageView.contentMode = UIViewContentModeScaleAspectFit;
        [self insertSubview:bgImageView belowSubview:self.mainView];
        self.backgroundImageView = bgImageView;
    }
    
    self.backgroundImageView.image = placeholderImage;
}

- (void)setImageURLStringsGroup:(NSArray *)imageURLStringsGroup
{
    _imageURLStringsGroup = imageURLStringsGroup;
    
    [self.backgroundImageView removeFromSuperview];

**Comment by gsdios** [comment]
具体什么问题呢？

**Comment by gsdios** [comment]
后来，已经修改过了，再下载测试下
