### ISSUE TITLE
当刷新 advCycleScrollView.imageURLStringsGroup的数组时显示会出现问题

### ISSUE THREAD

**Issue by RookieNeo** [gsdios/SDCycleScrollView#152]
当下拉刷新数据重新添加 advCycleScrollView.imageURLStringsGroup的数组时，分页的圆圈显示到第一个了但是图片却还是原来位置上的图片  下一秒也直接跳到刷新之前的位置  比如 在显示第三个图片的时候我下拉刷新 重新添加imageURLStringsGroup组数 ，这时候分页符号跳回到第一个 图片还是第三张 然后下次跳动直接跳到第四张去了

**Comment by gsdios** [comment]
已经修复过了，可以下载最新代码测试下
