### ISSUE TITLE
代理方法输出页码索引不正确。

### ISSUE THREAD

**Issue by jinxiansen** [gsdios/SDCycleScrollView#157]
-(void)cycleScrollView:(SDCycleScrollView *)cycleScrollView didScrollToIndex:(NSInteger)index
拖动图片的时候。

**Comment by auqarius** [comment]
同样发现这样的问题，如果手指快速滑动短距离导致滑动切换轮播图就会出现这样的问题，如果是手指慢慢带着图片一点点走直到滑动结束，那么返回的 inde 是对的。

**Comment by gsdios** [comment]
已经修复过这个问题了，请下载最新代码测试下
