### ISSUE TITLE
反馈一些东西.

### ISSUE THREAD

**Issue by hstdt** [gsdios/SDCycleScrollView#16]
感谢这个控件,我从中学习了不少东西,尤其是线程和缓存.同时发现了一些问题,仅供您参考.
1.timer的invalidate有疏漏
-(void)setAutoScrollTimeInterval:(CGFloat)autoScrollTimeInterval
{
    _autoScrollTimeInterval = autoScrollTimeInterval;
    [self setupTimer];
}
每设置一次autoScrollTimeInterval就会多一个timer.
同理还有这里 - (void)setImagesGroup:(NSMutableArray *)imagesGroup.
在setupTimer中一次性加上其他地方写过的  
 [_timer invalidate];
 _timer = nil;
2.建议用约束写collectionView和pageControl,就能在xib中用约束直接这个控件;
3.建议增加placeholderImage和pageControlBackgroundColor属性.
4..pageControl的valuechange事件也可以带动scrollView的滚动

**Comment by gsdios** [comment]
好的，这个timer问题有避免的，只不过把判断写进setupTimer会更好些，谢谢您的关注与支持，随后会继续优化的。
