### ISSUE TITLE
能不能增加个对PageControl的frame设置的接口

### ISSUE THREAD

**Issue by wzpforowrk** [gsdios/SDCycleScrollView#161]
因为PageControl的位置有可能需要上下调整

**Comment by lausen34** [comment]
SDCycleScrollView确实很强大,但是有时候,可能需要调整pageControl的frame,所以能不能增加一个接口给使用者,

**Comment by songhailiang** [comment]
同样遇到这样的问题，建议增加一个设置pageControl offset的属性来调整偏移量

**Comment by songhailiang** [comment]
我现在是这么解决的，新建了一个类继承自SDCycleScrollView，增加了一个属性：
`@property (nonatomic, assign) CGPoint pageControlOffset;`
然后重写layoutSubviews方法：
`- (void)layoutSubviews {

    [super layoutSubviews];
    
    //调整pageControl的偏移量
    if (!CGPointEqualToPoint(CGPointZero, self.pageControlOffset)) {
        UIPageControl *pageControl = [self pageControlInSDCycleScrollView];
        if (pageControl ) {
            CGRect frame =  pageControl.frame;
            frame.origin.x += self.pageControlOffset.x;
            frame.origin.y += self.pageControlOffset.y;
            pageControl.frame = frame;
        }
    }
}

- (UIPageControl *)pageControlInSDCycleScrollView {

    for (UIView *subview in self.subviews) {
        if ([subview isKindOfClass:[UIPageControl class]]) {
            return (UIPageControl *)subview;
        }
    }
    return nil;
}`
使用的时候，直接使用这个子类View

**Comment by gsdios** [comment]
已经增加pagecontrol偏移量设置接口
