### ISSUE TITLE
图片的 contentMode 不能修改 没留接口

### ISSUE THREAD

**Issue by lishulong199253** [gsdios/SDCycleScrollView#164]
请求下来的图片的比例可能跟设置的不一致, cell 上的imageview 的content mode 不能设置？

**Comment by ACoderBear** [comment]
请仔细查看头文件中的自定义接口 bannerImageViewContentMode 属性，可以设置。

**Comment by lishulong199253** [comment]
恩 用的是原来老的版本,新版本发现了。不好意思

**Comment by 54dujianchao** [comment]
我改了，但是 并没生效
