### ISSUE TITLE
双指点击才能触发代理方法

### ISSUE THREAD

**Issue by XianRong** [gsdios/SDCycleScrollView#179]
我遇到一个比较奇特的问题，在scrollView添加一个imageView,再在imageView上添加SDcycleScrollView,点击图片的代理方法需要双指才能触发，在其他地方能正常单指触发。

**Comment by gsdios** [comment]
能不能发个demo给我看下

**Comment by yanashenyang** [comment]
我也碰到这个问题了，单鸡没效果，双击才走代理点击方法
