### ISSUE TITLE
建议SDCycleScrollView下loadImageAtIndex函数这里改下

### ISSUE THREAD

**Issue by gjslitao** [gsdios/SDCycleScrollView#18]
容易出现-[__NSCFString absoluteURL]: 错误
一般出现这种情况，是在请求图片的时候，把NSURL连接直接用NSString 拼接了。 偶尔你用NSString拼接不会出现error，但是会莫名其妙的出现这样的问题，所以在用到请求图片的时候一定注意
建议改为如下:
NSURL *url = [NSURL URLWithString:[NSString stringWithFormat:@"%@", self.imageURLsGroup[index]]];
//NSURL *url = self.imageURLsGroup[index];

**Comment by gsdios** [comment]
好的，谢谢，我们会做进一步优化的
