### ISSUE TITLE
加在view上时collectionView向上偏移大约20，下边的pagecontrol背景灰色

### ISSUE THREAD

**Issue by BytemanDev** [gsdios/SDCycleScrollView#180]
给的demo都是加在scrollView上，只有add在view上时会出现偏移问题，另外利用dispatch_after延时加载网络图片不会出现偏移，但是两个应用切换以后还是会出现偏移，而且console里会打印一大推警告，add在scrollView里没有这些问题。

**Comment by gsdios** [comment]
以下是本库的使用者给出的一些解决方法放在这里供大家参考： 在iOS 7以后，controller 会对其中唯一的scrollView或其子类调整内边距，从而导致位置不准确。设置self.automaticallyAdjustsScrollViewInsets = NO;或者controller中放置不止一个scrollView或其子类时，就不会出现这种问题。以上原因是我的猜测，只要我设置了 self.automaticallyAdjustsScrollViewInsets = NO就没有那个问题了。

**Comment by Xlff** [comment]
我也是添加在view上的 但是设置placeholderImage后 pagecontrol的位置就没有偏移了
