### ISSUE TITLE
有没有提供刷新网络图片的接口

### ISSUE THREAD

**Issue by HHQBOOK** [gsdios/SDCycleScrollView#184]
#遇到一种情况,当网络情况不好的时候,如果没有加载出来图片,那么再刷新的时候,轮播图片的内容还是不能显示出来,而其他的我如果开始的时候,网络状态不好,那么刷新的时候,如果网络状态变好了,那么图片就会加载出来,这是其他的.....我看到SDCycleScrollView 这个框架我只看到了reloadInputViews 这个接口.可是刷新刷不出来. 如果是我水平太低,没有看到其他接口,希望给我指出在哪里,如果确实有这样的小BUG,希望作者改进

**Comment by HHQBOOK** [comment]
#遇到一种情况,当网络情况不好的时候,如果没有加载出来图片,那么再刷新的时候,轮播图片的内容还是不能显示出来,而其他的我如果开始的时候,网络状态不好,那么刷新的时候,如果网络状态变好了,那么图片就会加载出来,这是其他的.....我看到SDCycleScrollView 这个框架我只看到了reloadInputViews 这个接口.可是刷新刷不出来. 如果是我水平太低,没有看到其他接口,希望给我指出在哪里,如果确实有这样的小BUG,希望作者改进

**Comment by gsdios** [comment]
这个应该和sdwebimage的图片网络图片加载策略有关，不过默认应该是加载失败下次会重新请求的吧，我随后测试看下
