### ISSUE TITLE
UICollectionViewFlowLayout is not defined when embed in navigation controller

### ISSUE THREAD

**Issue by RemmoYu** [gsdios/SDCycleScrollView#19]
Get below message when the controller is embed in navigation controller, please check it:
"The behavior of the UICollectionViewFlowLayout is not defined because: the item height must be less than the height of the UICollectionView minus the section insets top and bottom values."

**Comment by Sum123** [comment]
the behavior of the UICollectionViewFlowLayout is not defined because:
the item height must be less than the height of the UICollectionView minus the section insets top and bottom values.
