### ISSUE TITLE
出现了一个问题 the behavior of the UICollectionViewFlowLayout is not defined because 说collection有问题   这应该怎么搞啊 

### ISSUE THREAD

**Issue by MyOnlyOnlySunshine** [gsdios/SDCycleScrollView#212]
the behavior of the UICollectionViewFlowLayout is not defined because:
 
the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.

 The relevant UICollectionViewFlowLayout instance is <UICollectionViewFlowLayout: 0x7fb248f1ac90>, and it is attached to <UICollectionView: 0x7fb249845600; frame = (0 0; 375 200); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x7fb248da5b50>; layer = <CALayer: 0x7fb248d15340>; contentOffset: {0, -64}; contentSize: {0, 0}> collection view layout: <UICollectionViewFlowLayout: 0x7fb248f1ac90>.

 Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.

这是什么问题啊

**Comment by zhoujun706** [comment]
怎么解决的能否告知一下
