### ISSUE TITLE
先创建view 添加到父view后再复制网络图片 无法显示

### ISSUE THREAD

**Issue by bluesky0109** [gsdios/SDCycleScrollView#24]
//网络加载 --- 创建带标题的图片轮播器
//    SDCycleScrollView *cycleScrollView2 = [SDCycleScrollView cycleScrollViewWithFrame:CGRectMake(0, 320, w, 180) imageURLStringsGroup:imagesURLStrings];
    
    SDCycleScrollView *cycleScrollView2 = [[SDCycleScrollView alloc] initWithFrame:CGRectMake(0, 320, w, 180)];
    cycleScrollView2.pageControlAliment = SDCycleScrollViewPageContolAlimentRight;
    cycleScrollView2.delegate = self;
    cycleScrollView2.titlesGroup = titles;
    cycleScrollView2.dotColor = [UIColor yellowColor]; // 自定义分页控件小圆标颜色
    cycleScrollView2.placeholderImage = [UIImage imageNamed:@"placeholder"];
    [self.view addSubview:cycleScrollView2];
    
    
    cycleScrollView2.imageURLStringsGroup = imagesURLStrings;

很多时候开始时是不知道网络url的，基本先创建了view占位，当网络请求后拿到url时再赋值的，此时无法显示图片，或者切换显示图片显示的url源和个数时 显示的个数不对

建议 _totalItemsCount 跟 imagesGroup 和 infiniteLoop形成绑定关系 
- (void)setImagesGroup:(NSMutableArray *)imagesGroup
{
    _imagesGroup = imagesGroup;
    _totalItemsCount = self.infiniteLoop ? imagesGroup.count * 100 : imagesGroup.count;
    if (imagesGroup.count != 1) {
        if (self.autoScroll) {
            [self setupTimer];
        }
    } else {
        self.mainView.scrollEnabled = NO;
    }
    
    [self setupPageControl];
    [self.mainView reloadData];
}

而不是 和 是否加到 父视图形成绑定关系

- (void)willMoveToSuperview:(UIView *)newSuperview
{
    if (!newSuperview) {
        [_timer invalidate];
        _timer = nil;
    } else {
        _totalItemsCount = self.infiniteLoop ? self.imagesGroup.count * 100 : self.imagesGroup.count;
    }
}

**Comment by gsdios** [comment]
好的，确实是这样的，疏忽了，谢谢提醒。
