### ISSUE TITLE
重置数据源时 如果刚开始的图片数为1 后面的为多张 后面的无法手动滑动

### ISSUE THREAD

**Issue by bluesky0109** [gsdios/SDCycleScrollView#25]
同一个view开始数据源给1张图片，后面给多张图片 则后面的无法手动滑动了。
尤其是当 SDCycleScrollView 放在tableview中的cell上进行复用时，会频繁切换数据源

建议修改：
- (void)setImagesGroup:(NSMutableArray *)imagesGroup
{
    _imagesGroup = imagesGroup;
    if (self.infiniteLoop) {
        _totalItemsCount = imagesGroup.count * 100;
    }else{
        _totalItemsCount = imagesGroup.count;
    }
    
    if (imagesGroup.count != 1) {
        [self setAutoScroll:self.autoScroll];
        self.mainView.scrollEnabled = YES;
    } else {
        self.mainView.scrollEnabled = NO;
    }
    
    [self setupPageControl];
    [self.mainView reloadData];
}

**Comment by gsdios** [comment]
好的，已经调整，谢谢关注和支持，希望以后继续多多提出宝贵意见和建议，学习了。
