### ISSUE TITLE
HTTPS图片加载不出来，在iOS10没事 ，在10一下的系统  加载不出来

### ISSUE THREAD

**Issue by Sunny-guangge** [gsdios/SDCycleScrollView#250]

**Comment by BladeTail** [comment]
需要修改SDCycleScrollView显示图片的源码，查找 sd_setImageWithURL 设置图片的调用，并添加options参数传入值：SDWebImageAllowInvalidSSLCertificates即可。

**Comment by CoderKLTse** [comment]
@BladeTail 当Allow Arbitrary Loads 设为NO的时候，即使这样设好像也无效

**Comment by BladeTail** [comment]
@CoderKLTse 对的，前提是你的info配置文件要设置Allow Arbitrary Loads为YES（这个是全局的），不设置的话，就需要在SDWebImage里将对应的证书校验加进去才行。
