### ISSUE TITLE
额

### ISSUE THREAD

**Issue by xiaoxiaozai** [gsdios/SDCycleScrollView#253]
SDCycleScrollView/SDCycleScrollView/Lib/SDCycleScrollView/SDCycleScrollView.m
请问 243 -250行..
- (void)setInfiniteLoop:(BOOL)infiniteLoop
{
    _infiniteLoop = infiniteLoop;
    
    if (self.imagePathsGroup.count) {
        self.imagePathsGroup = self.imagePathsGroup;
    }
}

中if语句里面作用是啥...

**Comment by gsdios** [comment]
判断是否需要刷新
