### ISSUE TITLE
当数据源数量为1时 暂无设置控制pagecontrol隐藏的功能

### ISSUE THREAD

**Issue by bluesky0109** [gsdios/SDCycleScrollView#26]
当数据源数量为1时 暂无设置控制pagecontrol隐藏的功能

由于我自己项目需要 我暂时建议的修改如下
- (void)setupPageControl
{
    if (_pageControl) [_pageControl removeFromSuperview]; // 重新加载数据时调整
    
    if (_imagesGroup.count <=1) {
        _pageControl = nil;
        return;
    }
    
    TAPageControl *pageControl = [[TAPageControl alloc] init];
    pageControl.numberOfPages = self.imagesGroup.count;
    pageControl.dotColor = self.dotColor;
    [self addSubview:pageControl];
    _pageControl = pageControl;
}

希望主维护人员有时间的话能讲 自定义的pagecontrol换成系统自带的，并提供对应接口 控制数据源数量为1时是否隐藏功能，另希望能将项目配置为支持cocoapods的让更多人有更多的选择使用方式，非常感谢您分享的这个项目，希望能持续更新优化超越同类的第三方。

**Comment by gsdios** [comment]
好的，感谢支持与关注。
