### ISSUE TITLE
pod 之后怎么显示和现有库中的 SDWebImage 的版本冲突怎么解决?

### ISSUE THREAD

**Issue by OneWang** [gsdios/SDCycleScrollView#265]
- `SDWebImage (~> 4.0.0-beta2)` required by `Podfile`
- `SDWebImage (= 4.0.0-beta2)` required by `Podfile.lock`
- `SDWebImage (~> 3.7)` required by `SDCycleScrollView (1.65)`

**Comment by graceydb** [comment]
遇到一样的问题了 咋整，难道要降低SDWebImage的版本吗

**Comment by GanHuaLin** [comment]
同样遇到这个问题
- `SDWebImage (~> 4.0.0-beta2)` required by `Podfile`
- `SDWebImage (~> 3.7)` required by `SDCycleScrollView (1.65)`

**Comment by junedeyu** [comment]
我就是降低SDWebImage 的版本3.8.2  解决的
