### ISSUE TITLE
纯文字轮播希望可以加一个是否禁止手动滑动的属性

### ISSUE THREAD

**Issue by marlon2brando** [gsdios/SDCycleScrollView#271]

**Comment by Zhangguiguang** [comment]
我觉得这个功能你可以自己去添加：
1. 在 SDCycleScrollView.h 第102行添加
102 >> /** 是否手势滚动,默认Yes */
103 >> @property (nonatomic,assign) BOOL gestureScroll;

2. 在 SDCycleScrollView.m 第82行添加
82 >> _gestureScroll = YES;

3. 在 SDCycleScrollView.m 第293行修改
293 -- self.mainView.scrollEnabled = YES;
293 >>self.mainView.scrollEnabled = self.gestureScroll;
OK。

**Comment by gsdios** [comment]
禁止滑动？需要点击吗？
