### ISSUE TITLE
[问题]文字宽度大于轮播器宽度时， 文字多余部分如何设置换行？

### ISSUE THREAD

**Issue by Fezreal** [gsdios/SDCycleScrollView#274]
现在文字超出轮播器部分，是以....来显示的， 想让它另起一行（多余部分进入到下一次轮播，不是单纯的显示在第二行。）。

**Comment by Fezreal** [comment]
@gsdios

**Comment by Fezreal** [comment]
![image](https://cloud.githubusercontent.com/assets/6703674/22179621/308030e4-e094-11e6-9b14-16155650b928.png)
这样子加了，无法解决问题。

**Comment by gsdios** [comment]
多余部分进入到下一次轮播，不是单纯的显示在第二行？
