### ISSUE TITLE
响应者问题

### ISSUE THREAD

**Issue by hanjunqiang** [gsdios/SDCycleScrollView#277]
问题描述：
1，SDCycleScrollView放在customview中，
2，customview当做collectionview的头部，
3，滚动collectionview时，SDCycleScrollView会重置到第一张，并且SDCycleScrollView会失去响应。

**Comment by gsdios** [comment]
有demo吗，发我看下？

**Comment by hanjunqiang** [comment]
@gsdios 大神，这个响应者问题解决了？

**Comment by hanjunqiang** [comment]
解决了，创建位置放错了。不应该放在tableview的header中。
