### ISSUE TITLE
Framework问题

### ISSUE THREAD

**Issue by HaijunWei** [gsdios/SDCycleScrollView#331]
使用CocoaPods导入框架，打开use_frameworks!选项
#import <SDWebImageManager.h>
#import <UIImageView+WebCache.h>

这两个头文件导入会报错，我得手动修改成如下
#import "SDWebImageManager.h"
#import "UIImageView+WebCache.h"

这个是个问题么？

**Comment by DesmondPang** [comment]
Same. Help
