### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by zdrzdr** [gsdios/SDCycleScrollView#34]
1.回到后台后，没有设置不滚动。
2.如果设置滚动速率？

**Comment by gsdios** [comment]
// 是否自动滚动,默认Yes
@property(nonatomic,assign) BOOL autoScroll;    控制是否自动滚动

// 自动滚动间隔时间,默认2s
@property (nonatomic, assign) CGFloat autoScrollTimeInterval; 改变滚动时间间隔调节速率

更多详细设置请看下头文件

**Comment by zdrzdr** [comment]
回到后台，框架应该自己检测并且停住滚动呀？？？,滚动速率不是间隔时间，而是从一张视图滚动到另一张视图的速度！

**Comment by gsdios** [comment]
1.框架要尽量解耦，适用于尽量多的情况，要不要进入后台后停止滚动你自己的controller来决定，可能只有极少人需要这个功能。
2.滚动用的系统接口，本人尚未使用过系统对于滚动速度的相关接口，如果有请提示下我来给框架添加下这个功能。
