### ISSUE TITLE
从SDCycleScrollView的控制器进入其他控制器没有暂停

### ISSUE THREAD

**Issue by zdrzdr** [gsdios/SDCycleScrollView#35]

**Comment by gsdios** [comment]
设置 autoscrolltimeinterval maxfloat 停止滚动

**Comment by zdrzdr** [comment]
什么意思？

**Comment by gsdios** [comment]
cycleScrollView.autoscrolltimeinterval = maxfloat
或者
cycleScrollView.autoscroll = no;
