### ISSUE TITLE
-[NSURL length]: unrecognized selector sent to instance 0x7b6ae840

### ISSUE THREAD

**Issue by zdrzdr** [gsdios/SDCycleScrollView#36]

**Comment by gsdios** [comment]
传 url 字符串进去！

**Comment by zdrzdr** [comment]
框架不应该自己检测判断吗？

**Comment by gsdios** [comment]
// 网络图片 url string 数组
@property (nonatomic, strong) NSArray *imageURLStringsGroup;

接口.h文件已经标注清楚是 url string 数组，就是直接拿到网络请求的数据放过了就可以了，你又多包装了一层，费事还容易出错。当然了，多判断一下可能会强壮些，但是别人如果传的不是url 而是 其它类型的数组我们这里就没法一一判断了吧。所以还是引导性的要求传入字符串数组，毕竟网络请求返回的就是字符串嘛。
