### ISSUE TITLE
提个设计问题,应暴露子控件

### ISSUE THREAD

**Issue by cuiYuhe** [gsdios/SDCycleScrollView#360]
我的使用场景, 需要自定义UI:
1.label 富文本, 需要设置行间距
2.PageControl需要设置右对齐: 最右面的点与上面label最右边对齐
使用您的框架我只能修改内部的代码.
我的建议:直接暴露控件,或者提供返回控件的代理.
谢谢.

**Comment by gsdios** [comment]
目前已经有提供自定义轮播cell的代理方法
