### ISSUE TITLE
我1.66版本怎么没有禁止拖动的方法 cocoapods看了确实是1.66

### ISSUE THREAD

**Issue by burring55yali** [gsdios/SDCycleScrollView#363]

**Comment by GoldenRocking** [comment]
/** 滚动手势禁用（文字轮播较实用） */
- (void)disableScrollGesture;

**Comment by burring55yali** [comment]
我知道是这个方法 问题是我1.66版本上没有这个方法
![2017-08-15 10 02 10](https://user-images.githubusercontent.com/13936964/29299403-f4a5681a-81a0-11e7-9636-053f2796c2ba.png)

**Comment by GoldenRocking** [comment]
那就不知道了，我这里有，也是1.66

**Comment by gsdios** [comment]
此项更新在1.70及以上版本中
