### ISSUE TITLE
Bug提交: cellForItemAtIndexPath:方法里面, image是nil的时候, 没有给image赋值

### ISSUE THREAD

**Issue by shuima101** [gsdios/SDCycleScrollView#366]
这是原来的代码
UIImage *image = [UIImage imageNamed:imagePath];
 if (!image) {
       [UIImage imageWithContentsOfFile:imagePath];
}
cell.imageView.image = image;

**Comment by gsdios** [comment]
好的，感谢反馈，已修复。
