### ISSUE TITLE
  清除缓存 

### ISSUE THREAD

**Issue by zdrzdr** [gsdios/SDCycleScrollView#37]
[cycleScrollView2 clearCache] 应该学习sdwebImage，单例清除，而且是全局的

**Comment by gsdios** [comment]
所以cyclescrollview实例共用一块缓存存储空间，任何一个实例调用clearcache即可清除全部缓存，cyclescrollview的clearcache内部实现交给nsfilemanager单例的方法管理，全局的，单例管理。

**Comment by zdrzdr** [comment]
但是使用者如果在另一个类中，如何清除呢？你这个只是对象呀,难道还有创建一个对象？,拿不到这个对象怎么办？ SDWeb的--->SDWebImageManager * mgr = [SDWebImageManager sharedManager]; 
    [mgr.imageCache clearMemory]

**Comment by gsdios** [comment]
SDCycleScrollView的 ----> [[[SDCycleScrollView alloc] init] clearCache];
如果觉得这样不方便的话可以给出一个类方法接口。原理一样的，自己的缓存就是要自己管理的。另外一个类如果要管理这个类的缓存的话，就要导入那个类来进行相关处理。不管是单利还是新建对象，只要处理的缓存对象是唯一的，原理一样的。
