### ISSUE TITLE
Bug！ 4张图片，2或3个文字标题时，标题label显示有问题

### ISSUE THREAD

**Issue by splsylp** [gsdios/SDCycleScrollView#372]
当图片数组中有4张图片，但是标题数组中有3个标题时，正常情况下第4张图片应该是隐藏的，但是现在其下方的文字介绍显示出来了并且展示的是第一张图片的标题；同样2个标题4张图的时候也会触发！
已发起[pull request#371](https://github.com/gsdios/SDCycleScrollView/pull/371)

**Comment by gsdios** [comment]
图片数量和titile数量应该完全保持一致，否则无法确定图片和title的对应关系
