### ISSUE TITLE
SDWebImage 升级到4.1

### ISSUE THREAD

**Issue by wzi90921** [gsdios/SDCycleScrollView#376]
SDWebImage 升级到4.1，SDCycleScrollView 只能用1.3，麻烦把SDWebImage指向4.1

**Comment by DozEuto** [comment]
同求

**Comment by gsdios** [comment]
SDCycleScrollView的1.73版本已经升级过SDWebImage了

**Comment by ldy694** [comment]
[!] Unable to satisfy the following requirements:

- `SDWebImage (~> 4.1.2)` required by `Podfile`
- `SDWebImage (~> 4.0.0)` required by `SDCycleScrollView (1.73)`

我另一个库需要4.1版本，希望SDWebImage能升到最新版，谢谢
