### ISSUE TITLE
OC-图片适应问题

### ISSUE THREAD

**Issue by doomc** [gsdios/SDCycleScrollView#380]
可以新增加一个图片自适应吗。

**Comment by doomc** [comment]
可以新增加一个图片自适应吗。

**Comment by gsdios** [comment]
/** 轮播图片的ContentMode，默认为 UIViewContentModeScaleToFill */
@property (nonatomic, assign) UIViewContentMode bannerImageViewContentMode;

**Comment by doomc** [comment]
感谢解答




发自网易邮箱大师
在2017年09月04日 11:57，高少东 写道：

/** 轮播图片的ContentMode，默认为 UIViewContentModeScaleToFill */
@property (nonatomic, assign) UIViewContentMode bannerImageViewContentMode;
