### ISSUE TITLE
貌似在cocoapods搜索不到SDCycleScrollView

### ISSUE THREAD

**Issue by zdiovo** [gsdios/SDCycleScrollView#39]
$ pod search SDCyclescrollview
[!] Unable to find a pod with name matching `SDCyclescrollview'

**Comment by gsdios** [comment]
SDCycleScrollView  ,S大写的

**Comment by zdiovo** [comment]
pod search SDCycleScrollView
[!] Unable to find a pod with name matching `SDCycleScrollView'

**Comment by zdiovo** [comment]
真的找不到啊，
$ gem source -l
*** CURRENT SOURCES ***

http://ruby.taobao.org/
难道是我换了源的原因么？

**Comment by hongdong** [comment]
我也找不到

**Comment by gsdios** [comment]
你在你那里查下其它的库可以搜到吗，我这里可以搜到的哦

**Comment by hongdong** [comment]
![46bce80c-1255-437c-a718-51ed4b9ae96e](https://cloud.githubusercontent.com/assets/5499518/8510600/484dfd34-2324-11e5-9f8d-75c106ce8710.png)
搜到了、但是失败了  是怎么回事呢？

**Comment by zdiovo** [comment]
我搜素其他的就可以啊。

$ pod search AFNetworking

-> AFNetworking (2.5.4)

   A delightful iOS and OS X networking framework.

   pod 'AFNetworking', '~> 2.5.4'

   - Homepage: https://github.com/AFNetworking/AFNetworking

   - Source:   https://github.com/AFNetworking/AFNetworking.git

   - Versions: 2.5.4, 2.5.3, 2.5.2, 2.5.1, 2.5.0, 2.4.1, 2.4.0, 2.3.1, 2.3.0,

   2.2.4, 2.2.3, 2.2.2, 2.2.1, 2.2.0, 2.1.0, 2.0.3, 2.0.2, 2.0.1, 2.0.0,

   2.0.0-RC3, 2.0.0-RC2, 2.0.0-RC1, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.1,

   1.2.0, 1.1.0, 1.0.1, 1.0, 1.0RC3, 1.0RC2, 1.0RC1, 0.10.1, 0.10.0, 0.9.2,

   0.9.1, 0.9.0, 0.7.0, 0.5.1 







在2015年07月05 14时42分, "GSD_iOS"<notifications@github.com>写道:



你在你那里查下其它的库可以搜到吗，我这里可以搜到的哦

**Comment by zdiovo** [comment]
你问下作者吧。我现在都搜索不到。╮(╯▽╰)╭






在2015年07月05 14时45分, "hongdong"<notifications@github.com>写道:




搜到了、但是失败了  是怎么回事呢？

**Comment by gsdios** [comment]
现在还不能安装成功吗，为什么我这里可以呢，我随后测试下看看

**Comment by zdiovo** [comment]
╮(╯▽╰)╭，不可以。直接在git上下载了master了。需要额外配置么？






在2015年07月05 14时59分, "GSD_iOS"<notifications@github.com>写道:



现在还不能安装成功吗，为什么我这里可以呢，我随后测试下看看

**Comment by gsdios** [comment]
pod 'SDCycleScrollView','~> 1.3'  ，在 podfile 里写上这句就可以了，，还是下载不了的话我 随后测试下看什么原因

**Comment by zdiovo** [comment]
我在cocoapods官网测试了一下，可以找到。但是在在终端用pod search SDCycleScrollView就是找不到。。。

**Comment by zdiovo** [comment]
我也试过了在podfile里面直接加上pod 'SDCycleScrollView','~> 1.3'，貌似不可以，提示是这样的：
Update all pods
Analyzing dependencies
[!] Unable to find a specification for `SDCycleScrollView (~> 1.3)`
