### ISSUE TITLE
加载网络gif图片

### ISSUE THREAD

**Issue by starLover** [gsdios/SDCycleScrollView#395]
项目需支持网络gif图，希望可以加上这个功能

**Comment by gsdios** [comment]
网络gif图片应该是支持的，你遇到了什么问题呢？

**Comment by starLover** [comment]
我看SDWebImage4.0.3以后支持网络gif了，我把cell里面的UIImageView改为了FLAnimatedImageView，传入了gif的urlstring，才会播放gif
