### ISSUE TITLE
关于图片缓存

### ISSUE THREAD

**Issue by BaiCanLin** [gsdios/SDCycleScrollView#41]
图片缓存是无效的

**Comment by gsdios** [comment]
为什么会是无效的呢，你到app沙盒看下，cache里是不是有个sdcyclescrollview文件夹，里面是不是有缓存图片，还有，测试的时候不要调用clearcache方法

**Comment by BaiCanLin** [comment]
比如说我，缓存对应的 JSON 数据，里面有图片的URL，我有网络的时候加载过一次，然后，断网，再次运行加载对应的APP,并不会离线显示之前的图片，但是答应出来，之前缓存的 JSON 是存在的
