### ISSUE TITLE
强烈建议更新SDWebImage的版本依赖，SDWebImage的4.0.0版在图片多时，存在重大BUG

### ISSUE THREAD

**Issue by snrtdddf** [gsdios/SDCycleScrollView#419]
**#强烈建议更新SDWebImage的版本依赖至## 4.1.2。**

我的APP图片比较多，在多图缓存及展示的过程中，4.0.0的SD存在一个重大BUG，导致应用闪退。
现在4.1.2已经修复了这个BUG，烦请作者更新一下。

**Comment by xnxy** [comment]
同样建议更新SDWebImage

**Comment by gsdios** [comment]
已经更新。
