### ISSUE TITLE
内存使用过高什么情况

### ISSUE THREAD

**Issue by bcrystalest** [gsdios/SDCycleScrollView#424]
我在一个控制器只添加了SDCycleScrollView,然后调用了几张本地图片做数据源,内存爆炸了,150+MB,不知道是什么原因....
`
_scrollView = [SDCycleScrollView cycleScrollViewWithFrame:CGRectMake(0, 40,[UIScreen mainScreen].bounds.size.width, 300) imageNamesGroup:(NSArray *)_array];
[self.view addSubview:_scrollView];
_scrollView.autoScrollTimeInterval = 10;
_scrollView.delegate = self;`

**Comment by gsdios** [comment]
要看你加载的什么图片，确认下是不是图片本身较大

**Comment by bcrystalest** [comment]
图片本身不大的,我删了页面重写,再重启了xcode就正常了....
