### ISSUE TITLE
循环的时候,图片数组是放大100倍的,这个是有性能问题的......

### ISSUE THREAD

**Issue by ios-zhouyu** [gsdios/SDCycleScrollView#427]
循环的时候,图片数组是放大100倍的,这个是有性能问题的......
能否使用imgGroup.count+2的模式进行处理?

![image](https://user-images.githubusercontent.com/19289675/32611430-499228ea-c52b-11e7-94ad-f025d4546c45.png)

**Comment by mTerminal** [comment]
大兄弟，这有啥性能问题？你改成 10000，也是两三个来回循环。
collectionView 复用啊。

**Comment by gsdios** [comment]
这个循环有多重实现方式，但是sd目前的方式应该没有性能问题

**Comment by bluesky0109** [comment]
@gsdios 我也曾经为该项目贡献过微博之力，上面 使用者提的 性能疑虑是很正常的。
1. 麻烦您 给出明确的 测试验证确认没有性能问题 再关闭issue
2. 即使 真的没有性能问题，也请 详细解释下 通过何种方式 怎么解决这个 隐藏的性能问题，让使用者放心使用，而不是 应该没有性能问题 然后就把 issue关闭了

**Comment by slemon** [comment]
@bluesky0109   UICollectionView Cell 会被复用，内存里面只会有你传入的图片个数
