### ISSUE TITLE
不会自动滚动 iOS11模拟器测试 代码如图

### ISSUE THREAD

**Issue by KaiJChen** [gsdios/SDCycleScrollView#429]
<img width="909" alt="wx20171113-181536 2x" src="https://user-images.githubusercontent.com/17287436/32720561-8c8ae320-c829-11e7-94db-c0d93aae793b.png">

**Comment by KaiJChen** [comment]
发现不是上面代码的问题 而是这个view存在但是图片数组刷新的问题 不能直接给imageURLStringsGroup赋值 这样回把定时器给关闭了。

**Comment by sdlbp** [comment]
@KaiJChen  不能直接给imageURLStringsGroup赋值 这样回把定时器给关闭了。 应该如何赋值

**Comment by KaiJChen** [comment]
@sdlbp   if(imageUrlList.count>1)self.bannerScrollView.autoScroll = YES; 重新设置一下autoScroll就可以了
