### ISSUE TITLE
数据源从0或1到多张的时候，轮播不会自动开始

### ISSUE THREAD

**Issue by lukenowre** [gsdios/SDCycleScrollView#437]
是因为数据源为0的时候，把autoscroll属性置为了No，但是刷新数据，重新走setImagePathsGroup方法的时候，用的是 [self setAutoScroll:self.autoScroll]，此时autoscroll为No，在别的地方也没有改变，所以就不会自动轮播，除非程序杀死重新创建

**Comment by gsdios** [comment]
已修复
