### ISSUE TITLE
我自定义的cell为什么显示不出来啊，是方法不对吗？

### ISSUE THREAD

**Issue by billlk123** [gsdios/SDCycleScrollView#452]
我用xib自定义了一个继承于UICollectionViewCell的子类NewsCycleCell,
然后实现了下面的方法
- (Class)customCollectionViewCellClassForCycleScrollView:(SDCycleScrollView *)view {
    if (view == _newsCycleScrollView) {
        return [NewsCycleCell class];
    }
    return nil;
}

/** 如果你自定义了cell样式，请在实现此代理方法为你的cell填充数据以及其它一系列设置 */
- (void)setupCustomCell:(UICollectionViewCell *)cell forIndex:(NSInteger)index cycleScrollView:(SDCycleScrollView *)view {
    if (view == _newsCycleScrollView) {
        NewsCycleCell *cycleCell = (NewsCycleCell *)cell;
        cycleCell.titleLabel.text = @"如何面对精神分裂的至亲？神经学家奥利弗萨克斯忆";
        cycleCell.newsImageView.image = [UIImage imageNamed:@"newsImage1"];
        cycleCell.timeAgoLabel.text = @"刚刚";
        cycleCell.browseNumLabel.text = @"8723";
    }
}

然后这个SDCycleScrollView是加在cell上的

**Comment by xavierXing** [comment]
@billlk123 

/** 如果你需要自定义cell样式，请在实现此代理方法返回你的自定义cell的Nib。 */
- (UINib *)customCollectionViewCellNibForCycleScrollView:(SDCycleScrollView *)view;

看 API 是个好习惯

**Comment by billlk123** [comment]
我用CocoaPods集成的，没看到有这个API啊
