### ISSUE TITLE
加载不出图片

### ISSUE THREAD

**Issue by ZZEmmaZhang** [gsdios/SDCycleScrollView#453]
self.bannerView.imageURLStringsGroup = @[@"http://static.babymoney.cn/upload/banner/%E7%A6%8F%E5%88%A9banner-03.png",@"http://static.babymoney.cn/upload/banner/%E6%97%A6%E6%84%BF%E6%9C%89%E7%A4%BCbanner_750x380px.png"];
}
无法显示图片。

**Comment by IosSuperman** [comment]
你的问题解决了吗？解决了的话是怎么好的？
