### ISSUE TITLE
一个潜在bug，导致越界crash

### ISSUE THREAD

**Issue by VVnx** [gsdios/SDCycleScrollView#47]
- (void)automaticScroll
{
    if (0 == _totalItemsCount) return;
    int currentIndex = _mainView.contentOffset.x / _flowLayout.itemSize.width;
    int targetIndex = currentIndex + 1;
    if (targetIndex == _totalItemsCount) {
        if (self.infiniteLoop) {
            targetIndex = _totalItemsCount * 0.5;
        }else{
            targetIndex = 0;
        }
        [_mainView scrollToItemAtIndexPath:[NSIndexPath indexPathForItem:targetIndex inSection:0] atScrollPosition:UICollectionViewScrollPositionNone animated:NO];
    }
    [_mainView scrollToItemAtIndexPath:[NSIndexPath indexPathForItem:targetIndex inSection:0] atScrollPosition:UICollectionViewScrollPositionNone animated:YES];
}

上面这个函数，在横竖屏切换时，可能导致targetIndex > _totalItemCount，导致越界crash。是否用一个内部的变量控制index，而不是根据contentOffset来判断index。

**Comment by gsdios** [comment]
这个库设计的时候没有考虑到横屏适配，在以后的更新版本中会做相关优化控制的。
