### ISSUE TITLE
请问这种页面的banner配合该框架要怎么做呢?我已经自定义cell但不是不知道如何每次滚动1/3让其他2个cell也露一点出来

### ISSUE THREAD

**Issue by sushushu** [gsdios/SDCycleScrollView#474]
http://ww1.sinaimg.cn/large/0061KoHBgy1fph8cx83x7j30fc0p8mz4.jpg

**Comment by sushushu** [comment]
@gsdios

**Comment by BruceWee01** [comment]
@sushushu  你这种需求实现了吗？

**Comment by sushushu** [comment]
@BruceWee01  自定义cell还做成圆角样式,但是不知道如何自定义collectionLayout 让其他2个cell也露一点出来

**Comment by BruceWee01** [comment]
@sushushu 那就是要自定义布局咯 我去看一下 正好也有你这种需求

**Comment by webersongao** [comment]
@sushushu 同样在考虑这个怎么实现？呜呜

**Comment by sushushu** [comment]
首先自定义cell,然后修改源码可以修改collectionLayout,我的qq 1404565175 可以一起讨论下 @BruceWee01 @webersongao
