### ISSUE TITLE
多图片标题不显示问题

### ISSUE THREAD

**Issue by blmyself** [gsdios/SDCycleScrollView#49]
我的环境是xcode6.4  iOS sdk 8.4， 图片全部对应的设置了标题，显示时，有的显示了，有的不显示，
如图：（第一个没有，第二个又有了）
![qq20150731-1](https://cloud.githubusercontent.com/assets/914295/8999728/1455451c-3771-11e5-8b98-374385ff9b85.png)
![qq20150731-3](https://cloud.githubusercontent.com/assets/914295/8999792/d97402f2-3771-11e5-9333-08beb268d507.png)
自己调试了下，发现是collection view的cell布局问题，没有调用layoutsubviews方法，于是在- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath里加入下面两句:
    [cell setNeedsLayout];
    [cell layoutIfNeeded];
问题解决了。

**Comment by gsdios** [comment]
好的。我随后也测试修复下
