### ISSUE TITLE
在swift里用的时候出错:

### ISSUE THREAD

**Issue by zdiovo** [gsdios/SDCycleScrollView#54]
创建SDCycleScrollView的代码
let imgs = Array(arrayLiteral: "1.jpg","2.jpg","3.jpg","4.jpg","5.jpg","6.jpg")
let scv = SDCycleScrollView(frame: CGRect(x: 0, y: 44, width: UIScreen.mainScreen().bounds.width, height: 400), imagesGroup: imgs)
self.view.addSubview(scv)

出错的位置:
- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath
{
    SDCollectionViewCell *cell = [collectionView dequeueReusableCellWithReuseIdentifier:ID forIndexPath:indexPath];
    long itemIndex = indexPath.item % self.imagesGroup.count;
    UIImage *image = self.imagesGroup[itemIndex];

//if语句出错
    if (image.size.width == 0 && self.placeholderImage) {
        image = self.placeholderImage;
    }
    cell.imageView.image = image;
    if (_titlesGroup.count) {
        cell.title = _titlesGroup[itemIndex];
    }

**Comment by zdiovo** [comment]
错误信息:
DevBate[9962:299921] the behavior of the UICollectionViewFlowLayout is not defined because:

DevBate[9962:299921] the item height must be less than the height of the UICollectionView minus the section insets top and bottom values.

DevBate[9962:299921] -[Swift._NSContiguousString size]: unrecognized selector sent to instance 0x7f94c857aab0

**Comment by gsdios** [comment]
你好，你们项目现在已经开始用swift开发了吗，还是自己测试时候出的问题呢

**Comment by 1xiaocainiao** [comment]
我也是报这个错误,楼主是怎么解决的呢
