### ISSUE TITLE
NSURLConnection 已弃用 请用NSURLSession

### ISSUE THREAD

**Issue by zdrzdr** [gsdios/SDCycleScrollView#56]
- (nullable instancetype)initWithRequest:(NSURLRequest *)request delegate:(nullable id)delegate startImmediately:(BOOL)startImmediately NS_DEPRECATED(10_5, 10_11, 2_0, 9_0, "Use NSURLSession (see NSURLSession.h)");

**Comment by gsdios** [comment]
好的，随后我看下更新下
