### ISSUE TITLE
不兼容SDWebImage5.0版本

### ISSUE THREAD

**Issue by feonixsmj** [gsdios/SDCycleScrollView#564]
请将 SDCycleScrollView.m 中 [[[SDWebImageManager sharedManager] imageCache] clearDiskOnCompletion:nil]; 方法替换一下
+ (void)clearImagesCache
{
//    [[[SDWebImageManager sharedManager] imageCache] clearDiskOnCompletion:nil];
    
    [[[SDWebImageManager sharedManager] imageCache] clearWithCacheType:SDImageCacheTypeDisk completion:^{
        
    }];
}

**Comment by FunnyFzl** [comment]
SDWebImage 已更新 导致这个框架报错 请修复

**Comment by Lius1104** [comment]
please

**Comment by RtzX** [comment]
手动导入... 只能这样子了

**Comment by TangXiaoDe** [comment]
pod 'SDWebImage', '4.4.5'                 # 图片加载库，SDCycleScrollView会自动依赖，但5.0版本不兼容，所以手动指定

**Comment by popor** [comment]
好几天了,作者不维护了吗?

**Comment by gsdios** [comment]
今天会更新一下，稍后发布

**Comment by jijiucheng** [comment]
> 今天会更新一下，稍后发布

作者赶紧更新发布呀，我们这边还等着发版呢。。。。。。        -.-   -.-   -.-

**Comment by liubiqu** [comment]
手动修改一下就可以发布了

**Comment by gsdios** [comment]
已发布，请更新。SDCycleScrollView (1.80) successfully published
