### ISSUE TITLE
头部出现一块灰色背景，图片向下移动了一块

### ISSUE THREAD

**Issue by qufuhai** [gsdios/SDCycleScrollView#57]

**Comment by qufuhai** [comment]
在StroyBoard中添加该控件，之后程序中这样处理
    imageScroll.imageURLStringsGroup = images;
    imageScroll.pageControlAliment = SDCycleScrollViewPageContolAlimentRight;
    imageScroll.delegate = self;
    imageScroll.titlesGroup = titles;
    imageScroll.dotColor = [UIColor yellowColor]; 
将会导致初始化时图片下移，背景显示出一块灰色区域。但是当迁移至其他页面再迁回时便正常。该控件按上述处理方式，在Tableview中是正常显示。

**Comment by gsdios** [comment]
具体情况截图我看下

**Comment by gsdios** [comment]
以下是本库的使用者给出的一些解决方法放在这里供大家参考：
在iOS 7以后，controller 会对其中唯一的scrollView或其子类调整内边距，从而导致位置不准确。设置self.automaticallyAdjustsScrollViewInsets = NO;或者controller中放置不止一个scrollView或其子类时，就不会出现这种问题。以上原因是我的猜测，只要我设置了 self.automaticallyAdjustsScrollViewInsets = NO就没有那个问题了。

**Comment by gsdios** [comment]
新建QQ交流群：185534916，欢迎加入！

**Comment by zzq1059201979** [comment]
[![simulator screen shot 2016 5 14 3 42 44](https://cloud.githubusercontent.com/assets/16394998/15267110/3af56352-19eb-11e6-8c0c-abe68e131195.png)
](url)我也遇到了这个问题，能看看问题出哪了？

**Comment by gsdios** [comment]
以下是本库的使用者给出的一些解决方法放在这里供大家参考：
在iOS 7以后，controller 会对其中唯一的scrollView或其子类调整内边距，从而导致位置不准确。设置self.automaticallyAdjustsScrollViewInsets = NO;或者controller中放置不止一个scrollView或其子类时，就不会出现这种问题。以上原因是我的猜测，只要我设置了 self.automaticallyAdjustsScrollViewInsets = NO就没有那个问题了。
