### ISSUE TITLE
cell的创建方法中，title的设置应该加判断条件，不然崩溃，还有title的重用问题

### ISSUE THREAD

**Issue by iosdeveloperpanc** [gsdios/SDCycleScrollView#61]
如果给的title的数组count小于cell的个数，那么就会出现title的重用问题，同时也会出现栈溢出，崩溃

**Comment by gsdios** [comment]
titile个数应该和image个数对应，没有title可以设置成空字符但title必须有，否则会崩溃

**Comment by iosdeveloperpanc** [comment]
不用对应，只要做判断就行了，少于image个数，对于title == nil的情况，不赋值即可

**Comment by gsdios** [comment]
那么哪个图片对应哪个title呢
