### ISSUE TITLE
当图片的张数为一张时应该隐藏pageControl

### ISSUE THREAD

**Issue by iosdeveloperpanc** [gsdios/SDCycleScrollView#63]
这个可以让用户自己做，但是我觉得一张的时候显示pageControl很不妥，最好在setter重写中去做处理比较好

**Comment by gsdios** [comment]
好的，收到反馈，随后会进一步完善的

**Comment by gsdios** [comment]
已完善：

// 是否在只有一张图时隐藏pagecontrol，默认为YES
@property(nonatomic) BOOL hidesForSinglePage;

**Comment by iosdeveloperpanc** [comment]
还有个问题，可以不可以把图片的加载用block回调空出来，让用户自己去用AFN或者SDWebImage等等加载都可以。你可以在你的demo中用你的方法去load图片。如果这样的话，这个框架就更灵活更完善了，用户可以不改框架的情况下对缓存进行处理。

**Comment by gsdios** [comment]
随后会进一步优化的
