### ISSUE TITLE
pageControl的控制太少了，不能定制出自己的样式

### ISSUE THREAD

**Issue by zhanjiarong** [gsdios/SDCycleScrollView#65]
pageControl的控制太少了，不能定制出自己的样式，比如要小圆点的颜色，只提供了当前小圆点的颜色设置，其它小圆点也要设置，还有pageControl的位置也要可以控制。我现在用了但是不符合工程需求

**Comment by gsdios** [comment]
pagecontrol的普通和当前颜色接口已经给出
