### ISSUE TITLE
不兼容ios6好像

### ISSUE THREAD

**Issue by BulletTrain** [gsdios/SDCycleScrollView#66]

**Comment by gsdios** [comment]
系统报错还是布局问题呢，详细说下或者截图看下

**Comment by BulletTrain** [comment]
podfile 设置platform :ios, '6.0' 后pod install就报错

[!] Unable to satisfy the following requirements:

- `SDCycleScrollView (~> 1.3)` required by `Podfile`
- `SDCycleScrollView (= 1.3)` required by `Podfile.lock`

Specs satisfying the `SDCycleScrollView (~> 1.3)` dependency were found, but they required a higher minimum deployment target.

Specs satisfying the `SDCycleScrollView (= 1.3)` dependency were found, but they required a higher minimum deployment target.

设置7.0就没问题

**Comment by gsdios** [comment]
哦，这个 当时spec 文件设置确实是7.0 "platforms": { "ios": "7.0"}

**Comment by BulletTrain** [comment]
能兼容下ios6么

**Comment by gsdios** [comment]
这个我需要随后修改下posdspec 配置文件，你们现在还在适配ios6吗，你可以先把代码下载下来用，这个修改好像不能及时生效，要等一段时间

**Comment by BulletTrain** [comment]
是的，还有些iphone4用户是6.1.3的，没办法，谢谢了，回头我注意下

**Comment by BulletTrain** [comment]
你好，不知道你修改过posdspec 配置文件了么

**Comment by gsdios** [comment]
昨天尝试修改没有成功，我对cocoapods不太熟，要不你先下载代码来用吧，或者你有这个具体操作流程之类的发我参考我修改下
