### ISSUE TITLE
在StoryBoard中如何使用？

### ISSUE THREAD

**Issue by FireLee** [gsdios/SDCycleScrollView#7]
你好，在StoryBoard中试了试，始终无法显示。

**Comment by gsdios** [comment]
你好，已更新，请下载

**Comment by FireLee** [comment]
谢谢！已经可以显示图片，但是在图片上边有几像素的灰条，好像是cell的背景色？

**Comment by gsdios** [comment]
你改下背景色试下，如果有问题再反馈下

**Comment by FireLee** [comment]
刚发现底下有这么段输出：the behavior of the UICollectionViewFlowLayout is not defined because:
the item height must be less than the height of the UICollectionView minus the section insets top and bottom values.

**Comment by FireLee** [comment]
弄好了，一直忘了反馈，非常好用！
