### ISSUE TITLE
非主线程操作ui资源   [self.mainView reloadData];

### ISSUE THREAD

**Issue by sujiewen** [gsdios/SDCycleScrollView#73]
- (void)loadImageAtIndex:(NSInteger)index
{
    NSString *urlStr = self.imageURLStringsGroup[index];
    NSURL *url = [NSURL URLWithString:urlStr];
    
    UIImage *image = [[SDImageCache sharedImageCache] imageFromDiskCacheForKey:urlStr];
    if (image) {
        [self.imagesGroup setObject:image atIndexedSubscript:index];
    } else {
        [[SDWebImageDownloader sharedDownloader] downloadImageWithURL:url options:SDWebImageDownloaderUseNSURLCache progress:nil completed:^(UIImage *image, NSData *data, NSError *error, BOOL finished) {
            if (image) {
                [self.imagesGroup setObject:image atIndexedSubscript:index];
                [self.mainView reloadData];
            }
        }];
    }
}

**Comment by gsdios** [comment]
好的，谢谢提醒，已修复。
