### ISSUE TITLE
内存激增

### ISSUE THREAD

**Issue by Deeer** [gsdios/SDCycleScrollView#74]
尝试图片加载后内存猛增近两百兆。不知是什么情况

**Comment by gsdios** [comment]
1.查看有无内存泄露
2.加载了多少张图片
3.使用代码截图给我看下

**Comment by Deeer** [comment]
6张图，其中两张比较大6M左右

- (SDCycleScrollView *)imgScrollview
{
    if (!_imgScrollview)
    {
        _imgScrollview = [[SDCycleScrollView alloc] initWithFrame:CGRectMake(0, 0, SCREENWIDTH, 200.0/667*SCREENHEIGHT)];
        _imgScrollview.pageControlStyle = SDCycleScrollViewPageContolStyleNone;
        _imgScrollview.delegate = self;
        _imgScrollview.titlesGroup = self.titleArr;
        _imgScrollview.autoScrollTimeInterval = 2.0f;
        _imgScrollview.placeholderImage = [UIImage imageNamed:@"bigImg.jpg"];
        _imgScrollview.titlesGroup = self.titleArr;
        _imgScrollview.textAlignment = NSTextAlignmentCenter;
    }
    return _imgScrollview;
}

 [self.placeImgView addSubview:self.imgScrollview];
self.imgScrollview.imageURLStringsGroup = self.imgUrlArr;
 self.imgScrollview.titlesGroup = self.titleArr;

**Comment by Deeer** [comment]
问题解决了：不直接将图片赋值给cell，cell的image用sdWebimage下
