### ISSUE TITLE
动态修改imageURLStringsGroup 或者imagesGroup，会出现数组越界问题

### ISSUE THREAD

**Issue by sujiewen** [gsdios/SDCycleScrollView#75]
导致问题是以为[[SDWebImageDownloader sharedDownloader] downloadImageWithURL 还在下载，没有及时奇效，本来有4张图片下载，然后更新2张图片显示。上面4张图片还在下载？就会导致数据越界

**Comment by gsdios** [comment]
感谢持续关注！已经修复，可以下载最新代码测试下。
