### ISSUE TITLE
对Autolayout支持不好

### ISSUE THREAD

**Issue by lnlink** [gsdios/SDCycleScrollView#77]
这个ScrollView写的很好，但是我发现如果放在Autolayout中布局，启动的时候不能够正常显示，会显示一半图1一半图2的。虽然用作者Demo中的方法没有问题，但是大多情况我还是要依赖xib、sb进行布局，尤其是类似banner的东西我要通过比例来适应不同屏幕的高度用起来就会尤为的繁琐，希望作者能够解决这个问题，感谢作者提供源码

**Comment by pandaApe** [comment]
+1

**Comment by gsdios** [comment]
已经 对 xib初始化方式 进行优化，请下载最新代码测试下。
