### ISSUE TITLE
placeholderImage的问题

### ISSUE THREAD

**Issue by FWBGitHub** [gsdios/SDCycleScrollView#78]
先加载了总的view，再加载scrollView，scroll不知道为什么加载的比较慢，导致urlImage已经请求完成，所以直接placeholderImage瞬间跳过去了

**Comment by FWBGitHub** [comment]
但是还是谢谢作者，写的不错

**Comment by FWBGitHub** [comment]
我又重新看了一下，好像只有执行        cycleScrollView2.imageURLStringsGroup = imagesURLStrings;
这个方法的时候，才会加载cell中的imageView。

**Comment by gsdios** [comment]
更新：imageURLs数组为空时也显示占位图
