### ISSUE TITLE
运行起来直接奔溃哦

### ISSUE THREAD

**Issue by BaiCanLin** [gsdios/SDCycleScrollView#8]
运行起来直接奔溃哦

**Comment by gsdios** [comment]
报 什么错？详细说明下

**Comment by gsdios** [comment]
你好，昨天晚上用错误数据调试没给设置回来，现在解决了，你更新下代码 。

**Comment by BaiCanLin** [comment]
嗨 封装的很好哦,刚刚看到

**Comment by sunjames** [comment]
[SDCycleScrollView scrollViewDidScroll:]: message sent to deallocated instance 0x1446351f0

**Comment by gsdios** [comment]
请更新下最新代码试下

**Comment by sunjames** [comment]
bug 如果向一个方向滑100次就卡住了

**Comment by gsdios** [comment]
用的 假 无限缓存，大概 在 你的图片个数 * 50 此 滑动之后 就到头了，，不是手拖动状态的话 会自动调回到七点重新开始
