### ISSUE TITLE
不能reloadData, iamges数组为空 会报错.

### ISSUE THREAD

**Issue by TuWei1992** [gsdios/SDCycleScrollView#9]
RT

**Comment by gsdios** [comment]
最好按照提供给你的接口进行创建实例并初始化，如果使用其他方法，请不要遗漏设置imagesGroup 或者 imageURLsGroup，当你设置完成后，框架会在合适的时机自动reloadData

**Comment by TuWei1992** [comment]
我一开始要是没有数据,需要等待网络返回图片列表咋弄, 而且我还需要在viewdidload 的 时候将空间添加到view

**Comment by gsdios** [comment]
你好，请下载我最新的代码在看下效果
