### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by loverjiao0321** [gsdios/SDCycleScrollView#96]
能否提供以model的形式传入数组，因为大部分图片都是有点击效果的，model中应至少包含id，imageUrl和titleStr类似的

**Comment by gsdios** [comment]
点击效果可以在点击发生时调用到的代理方法里面实现即可，model的话不同开发者业务不同无法统一定制。

**Comment by loverjiao0321** [comment]
恩 好吧 反正都能实现
