### ISSUE TITLE
fork建议

### ISSUE THREAD

**Issue by LiuHengChina** [gsdios/SDCycleScrollView#99]
[链接]()https://github.com/LiuHengChina/XSDCycleScrollView)

###
因为业务需求需要图片以Center居中所以使用的XSDCycleScrollView，XSDCycleScrollView也是基本以您的库为基础做的修改，我又再次基础上把当前图片华东的index提了出来，基本就是把您的index属性暴露出来用ReactiveCocoa接了出来。
源码
@property (strong, nonatomic) IBOutlet SDCycleScrollView *imagewheel;
    @weakify(self)
    [RACObserve(self.imagewheel, indexOnPageControl) subscribeNext:^(id x) {
        @strongify(self)
        self.indexnow = [x integerValue];
    }];
###
希望您做版本迭代时候可以考虑我的需求。谢谢

**Comment by gsdios** [comment]
新建QQ交流群：185534916，欢迎加入！

**Comment by gsdios** [comment]
已经添加设置contentmode接口
